Related modal bootstrap
farridav/django-jazzmin pull request #187
Opened 2020-10-17 18:46 UTC by KarimTayie

First of all thanks for the job done on this amazing project.
Second, in this PR I have added a flag in jazzmin settings to render Django popups inside an iframe within bootstrap 4 modals.
This PR is heavily inspired by https://github.com/fabiocaccamo/django-admin-interface related model feature.

Before:
![Screenshot from 2020-10-17 20-44-45](https://user-images.githubusercontent.com/29521303/96351103-903f6500-10b9-11eb-9560-a13c51fe660c.png)

After:
![Screenshot from 2020-10-17 19-24-38](https://user-images.githubusercontent.com/29521303/96351109-96354600-10b9-11eb-8fad-eabec98bb526.png)

Feel free to leave any comments.

2020-10-18 15:23 UTC, farridav commented
I really like the idea of this, and thank you for your contribution!

I'm going to try and look over this during the week, mostly to ensure it has suitable levels of:

- maintainability
- jazzyness
- testing if necessary

2020-10-21 08:07 UTC, farridav requested changes
1. When an item is added via an n+1 popup it renders out a blank page and does not close, see 
![image](https://user-images.githubusercontent.com/2966253/96691279-a03a9b80-137c-11eb-8233-770d928a69e6.png)
2. The escape key can only close the latest popup, any underneath it are unclosable using escape
3. the dynamic modal need a couple of classes added to it (comment inline)

That's all I've found so far, generally the user experience is quite good, if we can address the above its good to go in.

2020-10-21 08:07 UTC, farridav commented on jazzmin/static/jazzmin/js/related-modal.js
> +            });
```javascript
            $.showModal({
                title: title,
                body: body,
                backdrop: false,
                modalDialogClass: "modal-dialog-centered modal-lg",
                modalClass: "fade modal-wide related-modal-" + relatedModalCounter,
            });
```

Adds `fade`, and `modal-wide` into modalClass

2020-10-22 01:55 UTC, KarimTayie commented
@farridav 
I have pushed new commits for the 3 above comments.

2020-10-22 07:54 UTC, farridav commented
Fantastic work! everything behaves nicely, this is a great feature

2020-10-22 07:54 UTC, merged